# Generated by Django 5.0.6 on 2024-05-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='garnishment_fees',
        ),
    ]
