# Generated by Django 5.0.6 on 2024-05-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='State',
            new_name='state',
        ),
        migrations.AddField(
            model_name='location',
            name='employer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='street',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
