# Generated by Django 5.0.9 on 2024-09-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='amount_to_withhold_child1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='amount_to_withhold_child2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='amount_to_withhold_child3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='amount_to_withhold_child4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='amount_to_withhold_child5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
