# Generated by Django 5.0.6 on 2024-05-31 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tax_details',
            old_name='employee_id',
            new_name='employer_id',
        ),
    ]
