# Generated by Django 4.2.1 on 2024-06-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='user',
        ),
    ]
