# Generated by Django 5.0.9 on 2024-09-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_rename_federal_income_single_student_loan_data_federal_income_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garcalculation_data',
            old_name='number_of_arrears',
            new_name='number_of_arrers',
        ),
        migrations.RenameField(
            model_name='multiple_student_loan_data_and_result',
            old_name='studentloan1',
            new_name='StudentLoanAmount1',
        ),
        migrations.RenameField(
            model_name='multiple_student_loan_data_and_result',
            old_name='studentloan2',
            new_name='StudentLoanAmount2',
        ),
        migrations.RenameField(
            model_name='multiple_student_loan_data_and_result',
            old_name='studentloan3',
            new_name='StudentLoanAmount3',
        ),
        migrations.AddField(
            model_name='calculation_data_results',
            name='number_of_garnishment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='net_pay',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garcalculation_data',
            name='number_of_garnishment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiple_student_loan_result',
            name='StudentLoanAmount1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiple_student_loan_result',
            name='StudentLoanAmount2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiple_student_loan_result',
            name='StudentLoanAmount3',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
