# Generated by Django 4.2.1 on 2024-07-31 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_remove_profile_user_delete_customuser_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application_activity',
            old_name='action',
            new_name='actions',
        ),
    ]
