# Generated by Django 4.2.1 on 2024-07-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_remove_logentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='minimun_wages',
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='net_pay',
        ),
        migrations.RemoveField(
            model_name='garcalculation_data',
            name='earning',
        ),
        migrations.AddField(
            model_name='garcalculation_data',
            name='support_second_family',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='pay_cycle',
            field=models.CharField(),
        ),
    ]
