# Generated by Django 5.0.9 on 2024-10-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_calculationresult_amount_to_withhold_child1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='arrears_amt_Child1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='arrears_amt_Child2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='arrears_amt_Child3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='arrears_amt_Child4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='arrears_amt_Child5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
