# Generated by Django 5.0.6 on 2024-05-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_remove_employee_details_garnishment_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='department',
            field=models.CharField(default='IT', max_length=50),
            preserve_default=False,
        ),
    ]
