# Generated by Django 4.2.1 on 2024-06-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_rename_employee_id_tax_details_employer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='minimun_wages',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='number_of_garnishment',
            field=models.IntegerField(max_length=50),
        ),
    ]
