# Generated by Django 4.2.1 on 2024-07-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0003_remove_employee_details_minimun_wages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garcalculation_data',
            old_name='total_amount_to_withhold',
            new_name='amount_to_withhold',
        ),
        migrations.RemoveField(
            model_name='garcalculation_data',
            name='have_any_arrears',
        ),
        migrations.AddField(
            model_name='garcalculation_data',
            name='earnings',
            field=models.FloatField(default=9.007),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garcalculation_data',
            name='employee_name',
            field=models.CharField(default='new'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garcalculation_data',
            name='minimum_wages',
            field=models.FloatField(default=777),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garcalculation_data',
            name='order_id',
            field=models.IntegerField(default=877655),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garcalculation_data',
            name='state',
            field=models.CharField(default='mp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdffile',
            name='employer_id',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
