# Generated by Django 5.0.6 on 2024-05-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0003_employee_details_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_profile',
            name='password',
            field=models.CharField(default='567844', max_length=50),
            preserve_default=False,
        ),
    ]
