# Generated by Django 4.2.1 on 2024-07-31 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0003_rename_action_application_activity_actions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application_activity',
            old_name='actions',
            new_name='action',
        ),
    ]
