# Generated by Django 5.0.9 on 2024-11-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0003_calculationresult_arrears_amt_child1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State_tax_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employer_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('gross_income', models.FloatField()),
                ('garnishment_fees', models.FloatField()),
                ('federal_tax', models.FloatField()),
                ('local_tax', models.FloatField()),
                ('medical_insurance', models.FloatField()),
                ('social_and_security', models.FloatField()),
                ('medicare_tax', models.FloatField()),
                ('state_tax', models.FloatField()),
                ('workers_compensation', models.FloatField()),
                ('SDI', models.FloatField()),
                ('union_due', models.FloatField()),
                ('credit_union', models.FloatField()),
                ('debt', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
