# Generated by Django 5.0.9 on 2024-09-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0003_rename_number_of_arrears_garcalculation_data_number_of_arrers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garcalculation_data',
            old_name='number_of_arrers',
            new_name='number_of_arrer',
        ),
    ]
