# Generated by Django 4.2.1 on 2024-06-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0003_alter_employee_details_minimun_wages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='employer_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='minimun_wages',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='number_of_garnishment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tax_details',
            name='employer_id',
            field=models.IntegerField(),
        ),
    ]
