# Generated by Django 4.2.1 on 2024-08-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0004_rename_actions_application_activity_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='action',
            new_name='actions',
        ),
    ]
