# Generated by Django 5.0.9 on 2024-09-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0004_rename_number_of_arrers_garcalculation_data_number_of_arrer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garcalculation_data',
            old_name='number_of_arrer',
            new_name='number_of_arrear',
        ),
    ]
