# Generated by Django 4.2.1 on 2024-06-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0004_alter_employee_details_employer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='employee_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
