# Generated by Django 5.0.6 on 2024-05-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0004_employer_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_profile',
            name='username',
            field=models.CharField(default='root', max_length=50),
            preserve_default=False,
        ),
    ]
