# Generated by Django 4.2.1 on 2024-07-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0004_rename_total_amount_to_withhold_garcalculation_data_amount_to_withhold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IWO_PDF_Files_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employer_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='PDFFile',
        ),
    ]
