# Generated by Django 5.0.9 on 2024-12-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0005_state_tax_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='state_tax_data',
            name='contribution',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state_tax_data',
            name='mexico_tax',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state_tax_data',
            name='united_way_contribution',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
