# Generated by Django 5.0.6 on 2024-05-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0005_employer_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_profile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='employer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='federal_employer_identification_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='number_of_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
