# Generated by Django 4.2.1 on 2024-07-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0005_iwo_pdf_files_data_delete_pdffile'),
    ]

    operations = [
        migrations.CreateModel(
            name='IWOPDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('employer_id', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IWO_PDF_Files_Data',
        ),
    ]
