# Generated by Django 4.2.1 on 2024-07-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0006_iwopdffile_delete_iwo_pdf_files_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iwopdffile',
            name='employer_id',
        ),
        migrations.RemoveField(
            model_name='iwopdffile',
            name='title',
        ),
    ]
