# Generated by Django 4.2.1 on 2024-06-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0006_remove_location_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='calculation_data',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('Earning', models.FloatField()),
                ('Taxes', models.CharField(max_length=100, unique=True)),
                ('FIT', models.FloatField()),
                ('social', models.FloatField()),
                ('medicare', models.FloatField()),
                ('state', models.FloatField()),
                ('garnishment_fees', models.CharField(blank=True, max_length=255, null=True)),
                ('arrears_greater_than_12_weeks', models.BooleanField()),
                ('minimun_wage', models.IntegerField(blank=True, null=True)),
                ('total_amount_to_withhold', models.FloatField()),
            ],
        ),
    ]
