# Generated by Django 4.2.1 on 2024-08-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0006_rename_actions_logentry_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax_details',
            name='SDI_tax',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
