# Generated by Django 4.2.1 on 2024-06-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0007_calculation_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculation_data',
            old_name='Earning',
            new_name='earning',
        ),
        migrations.RenameField(
            model_name='calculation_data',
            old_name='Taxes',
            new_name='taxes',
        ),
    ]
