# Generated by Django 5.0.9 on 2024-12-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0007_rename_fedral_income_tax_calculation_data_results_disposable_earnings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garcalculation_data',
            old_name='disposable_earnings',
            new_name='disposable_income',
        ),
    ]
