# Generated by Django 4.2.1 on 2024-07-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0007_remove_iwopdffile_employer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iwopdffile',
            name='employer_id',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iwopdffile',
            name='pdf_name',
            field=models.CharField(default='new', max_length=100),
            preserve_default=False,
        ),
    ]
