# Generated by Django 4.2.1 on 2024-07-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0008_iwopdffile_employer_id_iwopdffile_pdf_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iwopdffile',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
