# Generated by Django 4.2.1 on 2024-07-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0009_alter_iwopdffile_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iwopdffile',
            name='pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
