# Generated by Django 4.1.2 on 2024-08-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0010_federal_case_data_federal_case_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='head_of_household',
            name='exemptions_6',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='married_filing_joint_return',
            name='exemptions_6',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='married_filing_sepearte_return',
            name='exemptions_6',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='single_filing_status',
            name='exemptions_6',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
