# Generated by Django 4.2.1 on 2024-07-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0010_alter_iwopdffile_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='garcalculation_data',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2024-02-10 12:00:00'),
            preserve_default=False,
        ),
    ]
