# Generated by Django 5.0.9 on 2024-12-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0011_rename_disposable_earnings_multiple_student_loan_data_disposable_income_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiple_student_loan_data',
            old_name='disposable_income',
            new_name='disposable_earnings',
        ),
        migrations.RemoveField(
            model_name='federal_loan_case_data',
            name='earnings',
        ),
        migrations.RemoveField(
            model_name='federal_tax_data_and_result',
            name='earnings',
        ),
        migrations.RemoveField(
            model_name='multiple_student_loan_data',
            name='earnings',
        ),
        migrations.RemoveField(
            model_name='multiple_student_loan_data_and_result',
            name='earnings',
        ),
        migrations.RemoveField(
            model_name='single_student_loan_data',
            name='earnings',
        ),
        migrations.RemoveField(
            model_name='single_student_loan_data_and_result',
            name='earnings',
        ),
    ]
