# Generated by Django 4.2.1 on 2024-07-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0011_garcalculation_data_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='employer_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='iwo_details_pdf',
            name='employer_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='employer_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tax_details',
            name='employer_id',
            field=models.IntegerField(unique=True),
        ),
    ]
