# Generated by Django 4.1.2 on 2024-08-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0011_head_of_household_exemptions_6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head_of_household',
            name='pay_period',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='married_filing_joint_return',
            name='pay_period',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='married_filing_sepearte_return',
            name='pay_period',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='single_filing_status',
            name='pay_period',
            field=models.CharField(max_length=255),
        ),
    ]
