# Generated by Django 5.0.9 on 2024-12-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0012_rename_disposable_income_multiple_student_loan_data_disposable_earnings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiple_student_loan_data',
            old_name='disposable_earnings',
            new_name='disposable_income',
        ),
    ]
