# Generated by Django 5.0.9 on 2024-12-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0013_rename_disposable_earnings_multiple_student_loan_data_disposable_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='multiple_garnishment_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employer_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=255)),
                ('garnishment_fees', models.FloatField()),
                ('support_second_family', models.BooleanField()),
                ('arrears_greater_than_12_weeks', models.BooleanField(blank=True, null=True)),
                ('amount_to_withhold_child1', models.FloatField(blank=True, null=True)),
                ('amount_to_withhold_child2', models.FloatField(blank=True, null=True)),
                ('amount_to_withhold_child3', models.FloatField(blank=True, null=True)),
                ('amount_to_withhold_child4', models.FloatField(blank=True, null=True)),
                ('amount_to_withhold_child5', models.FloatField(blank=True, null=True)),
                ('arrears_amt_Child1', models.FloatField(blank=True, null=True)),
                ('arrears_amt_Child2', models.FloatField(blank=True, null=True)),
                ('arrears_amt_Child3', models.FloatField(blank=True, null=True)),
                ('arrears_amt_Child4', models.FloatField(blank=True, null=True)),
                ('arrears_amt_Child5', models.FloatField(blank=True, null=True)),
                ('number_of_garnishment', models.IntegerField()),
                ('number_of_arrear', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('disposable_income', models.FloatField()),
                ('pay_period', models.CharField(max_length=255)),
                ('filing_status', models.CharField(max_length=255)),
                ('no_of_exception', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='calculation_data_results',
            name='earnings',
        ),
        migrations.RemoveField(
            model_name='garcalculation_data',
            name='earnings',
        ),
    ]
