# Generated by Django 4.1.2 on 2024-08-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0013_alter_head_of_household_morethan6_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='federal_case_data',
            new_name='federal_loan_case_data',
        ),
    ]
