# Generated by Django 4.2.1 on 2024-07-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0014_application_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_activity',
            name='employer_name',
        ),
    ]
