# Generated by Django 4.2.1 on 2024-07-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0015_remove_application_activity_employer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_activity',
            name='employer_id',
        ),
    ]
