# Generated by Django 4.2.1 on 2024-07-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0016_remove_application_activity_employer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2024-07-19T12:34:56Z'),
            preserve_default=False,
        ),
    ]
