# Generated by Django 4.1.1 on 2024-08-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0019_federal_tax_data_and_result_amount_deduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federal_loan_case_data',
            name='order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiple_student_loan_result',
            name='order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_loan_data',
            name='order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
