# Generated by Django 5.0.10 on 2024-12-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0021_alter_multiple_garnishment_case_result_batch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federal_loan_case_data',
            name='order_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='garcalculation_data',
            name='order_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='multiple_garnishment_data',
            name='order_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='multiple_student_loan_data',
            name='order_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='single_student_loan_data',
            name='order_id',
            field=models.CharField(max_length=255),
        ),
    ]
