# Generated by Django 4.1.1 on 2024-08-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0021_student_loan_data_employee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='single_student_loan_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employer_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=255)),
                ('earnings', models.FloatField()),
                ('garnishment_fees', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='student_loan_data',
            new_name='multiple_student_loan_data',
        ),
    ]
