# Generated by Django 5.0.9 on 2024-12-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0022_state_tax_result_gross_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='garcalculation_data',
            name='pay_period',
            field=models.CharField(default='weekly', max_length=255),
            preserve_default=False,
        ),
    ]
