# Generated by Django 5.0.9 on 2024-12-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0022_alter_federal_loan_case_data_order_id_and_more'),
        ('User_app', '0024_alter_calculation_data_results_number_of_child_support_order_and_more'),
    ]

    operations = [
    ]
