# Generated by Django 5.0.9 on 2024-12-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0025_merge_20241224_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='number_of_child_support_order',
        ),
    ]
