# Generated by Django 5.0.9 on 2024-12-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0026_remove_employee_details_number_of_child_support_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='number_of_child_support_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
