# Generated by Django 5.0.9 on 2025-01-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0027_employee_details_number_of_child_support_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garcalculation_data',
            old_name='disposable_income',
            new_name='gross_pay',
        ),
        migrations.AddField(
            model_name='garcalculation_data',
            name='mandatory_deductions',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
