# Generated by Django 5.0.9 on 2025-01-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0028_rename_disposable_income_garcalculation_data_gross_pay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_details',
            old_name='employer_id',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='employee_details',
            old_name='department',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='employee_details',
            old_name='employee_name',
            new_name='filing_status',
        ),
        migrations.RenameField(
            model_name='employee_details',
            old_name='location',
            new_name='home_state',
        ),
        migrations.RenameField(
            model_name='employee_details',
            old_name='pay_cycle',
            new_name='marital_status',
        ),
        migrations.RenameField(
            model_name='employee_details',
            old_name='number_of_child_support_order',
            new_name='number_of_exemptions',
        ),
        migrations.RenameField(
            model_name='employer_profile',
            old_name='city',
            new_name='bank_account_number',
        ),
        migrations.RenameField(
            model_name='employer_profile',
            old_name='country',
            new_name='bank_name',
        ),
        migrations.RenameField(
            model_name='employer_profile',
            old_name='employer_id',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='employer_profile',
            old_name='employer_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='employer_profile',
            old_name='username',
            new_name='registered_address',
        ),
        migrations.RemoveField(
            model_name='employer_profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employer_profile',
            name='federal_employer_identification_number',
        ),
        migrations.RemoveField(
            model_name='employer_profile',
            name='number_of_employees',
        ),
        migrations.RemoveField(
            model_name='employer_profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='employer_profile',
            name='street_name',
        ),
        migrations.AddField(
            model_name='employee_details',
            name='blind',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_details',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_details',
            name='is_spouse_blind',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='number_of_student_default_loan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_details',
            name='pay_period',
            field=models.CharField(default='weekly', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_details',
            name='social_security_number',
            field=models.CharField(default=2334444, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_details',
            name='spouse_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='support_second_family',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_details',
            name='work_state',
            field=models.CharField(default='Florida', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer_profile',
            name='ein',
            field=models.IntegerField(default=1111),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='employee_id',
            field=models.CharField(max_length=255),
        ),
    ]
