# Generated by Django 5.0.9 on 2025-01-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0029_rename_employer_id_employee_details_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=255)),
                ('company_id', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('social_security_number', models.CharField(max_length=255)),
                ('blind', models.BooleanField()),
                ('home_state', models.CharField(max_length=255)),
                ('work_state', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_period', models.CharField(max_length=255)),
                ('number_of_exemptions', models.IntegerField()),
                ('filing_status', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=255)),
                ('number_of_student_default_loan', models.IntegerField()),
                ('support_second_family', models.BooleanField()),
                ('spouse_age', models.IntegerField(blank=True, null=True)),
                ('is_spouse_blind', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
