# Generated by Django 4.1.1 on 2024-08-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0030_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='employer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
