# Generated by Django 5.0.9 on 2025-01-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0030_employee_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_detail',
            name='blind',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
