# Generated by Django 5.0.9 on 2025-01-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0033_rename_bank_account_number_employer_profile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_id', models.IntegerField(max_length=255)),
                ('ein', models.IntegerField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('zipcode', models.IntegerField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('DBA_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
