# Generated by Django 5.0.9 on 2025-01-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0034_company_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_detail',
            name='employer_ids',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
