# Generated by Django 5.0.9 on 2025-01-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0035_employee_detail_employer_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_detail',
            name='employer_ids',
        ),
    ]
