# Generated by Django 5.0.9 on 2025-01-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0037_remove_employee_detail_employer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer_profile',
            old_name='employer_id',
            new_name='cid',
        ),
        migrations.RemoveField(
            model_name='calculation_data_results',
            name='employer_id',
        ),
        migrations.AddField(
            model_name='calculation_data_results',
            name='cid',
            field=models.CharField(default='C01', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_detail',
            name='cid',
            field=models.CharField(default='C01', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculation_data_results',
            name='employee_id',
            field=models.CharField(max_length=255),
        ),
    ]
