# Generated by Django 5.0.9 on 2025-01-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0038_rename_employer_id_employer_profile_cid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='peo_table',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('peo_id', models.AutoField(primary_key=True, serialize=False)),
                ('peo_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password1', models.CharField(max_length=255)),
                ('password2', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='employer_profile',
            old_name='cid',
            new_name='employer_id',
        ),
    ]
