# Generated by Django 5.1.5 on 2025-01-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0039_peo_table_rename_cid_employer_profile_employer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_detail',
            old_name='employee_id',
            new_name='e_id',
        ),
    ]
