# Generated by Django 5.1.5 on 2025-01-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0040_rename_employee_id_employee_detail_e_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_detail',
            old_name='e_id',
            new_name='ee_id',
        ),
    ]
