# Generated by Django 5.1.5 on 2025-01-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0041_rename_e_id_employee_detail_ee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='registered_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
