# Generated by Django 5.1.5 on 2025-01-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0043_remove_employee_detail_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='co_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='ein',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
