# Generated by Django 5.0.9 on 2025-01-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0040_alter_company_details_co_id_and_more'),
        ('User_app', '0044_alter_company_details_co_id_and_more'),
    ]

    operations = [
    ]
