# Generated by Django 5.0.9 on 2025-01-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0045_merge_20250124_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_details',
            old_name='co_id',
            new_name='cid',
        ),
    ]
