# Generated by Django 5.0.9 on 2025-01-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0045_merge_20250124_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='peo_tb',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('peo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.CharField(default='ABS', max_length=100)),
                ('employer_name', models.CharField(default='ABS', max_length=100)),
                ('email', models.EmailField(default='rtt@gmail.com', max_length=254, unique=True)),
                ('username', models.CharField(default='USN', max_length=100, unique=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('federal_employer_identification_number', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_employees', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Employer_Profile',
        ),
        migrations.DeleteModel(
            name='peo_table',
        ),
        migrations.RenameField(
            model_name='company_details',
            old_name='co_id',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='company_details',
            old_name='DBA_name',
            new_name='dba_name',
        ),
    ]
