# Generated by Django 5.0.9 on 2025-01-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0046_rename_co_id_company_details_cid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_profile',
            name='cid',
            field=models.CharField(default='ABS', max_length=100),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='cid',
            field=models.CharField(max_length=255),
        ),
    ]
