# Generated by Django 5.0.9 on 2025-01-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0047_employer_profile_cid_alter_company_details_cid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company_details',
        ),
    ]
