# Generated by Django 5.0.9 on 2025-01-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0048_delete_company_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=255)),
                ('ein', models.IntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('registered_address', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('dba_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
