# Generated by Django 5.0.9 on 2025-01-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0049_company_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_detail',
            old_name='blind',
            new_name='is_blind',
        ),
    ]
