# Generated by Django 5.0.9 on 2025-01-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0051_payroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='garnishment_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('eeid', models.IntegerField()),
                ('case_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('sdu', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, max_length=255, null=True)),
                ('end_date', models.DateField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=250)),
                ('arrear_greater_than_12_weeks', models.BooleanField(default=False)),
                ('arrear_amount', models.DecimalField(decimal_places=2, max_digits=250)),
            ],
        ),
    ]
