# Generated by Django 5.0.9 on 2025-01-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0053_rename_deductions_payroll_deduction_401k_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garnishment_order',
            name='eeid',
        ),
    ]
