# Generated by Django 5.0.9 on 2025-01-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0053_rename_deductions_payroll_deduction_401k_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garnishment_order',
            name='cid',
            field=models.CharField(default='C00001', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garnishment_order',
            name='eeid',
            field=models.CharField(max_length=254),
        ),
    ]
