# Generated by Django 5.0.9 on 2025-01-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0054_garnishment_order_cid_alter_garnishment_order_eeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='record_import',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company_details',
            name='record_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_detail',
            name='record_import',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_detail',
            name='record_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garnishment_order',
            name='record_import',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garnishment_order',
            name='record_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
