# Generated by Django 5.0.9 on 2025-01-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0054_remove_garnishment_order_eeid'),
        ('User_app', '0055_company_details_record_import_and_more'),
    ]

    operations = [
    ]
