# Generated by Django 5.0.9 on 2025-01-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0056_merge_20250127_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iwo_details_pdf',
            old_name='employer_id',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='iwo_details_pdf',
            old_name='employee_id',
            new_name='ee_id',
        ),
        migrations.AddField(
            model_name='garnishment_order',
            name='eeid',
            field=models.CharField(default='C00001', max_length=254),
            preserve_default=False,
        ),
    ]
