# Generated by Django 5.0.9 on 2025-01-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0057_rename_employer_id_iwo_details_pdf_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iwo_details_pdf',
            name='cid',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='iwo_details_pdf',
            name='ee_id',
            field=models.CharField(max_length=250),
        ),
    ]
