# Generated by Django 5.0.9 on 2025-01-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0058_alter_iwo_details_pdf_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='record_import',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-29T07:05:25Z'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company_details',
            name='record_updated',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-29T07:05:25Z'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_detail',
            name='record_import',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-29T07:05:25Z'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_detail',
            name='record_updated',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-29T07:05:25Z'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garnishment_order',
            name='record_import',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-29T07:05:25Z'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garnishment_order',
            name='record_updated',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-29T07:05:25Z'),
            preserve_default=False,
        ),
    ]
